add_test( GraphTest.BasicInsert /home/xjdr/src/xjdr/gg/tests/graph_test [==[--gtest_filter=GraphTest.BasicInsert]==] --gtest_also_run_disabled_tests)
set_tests_properties( GraphTest.BasicInsert PROPERTIES WORKING_DIRECTORY /home/xjdr/src/xjdr/gg/tests VS_DEBUGGER_WORKING_DIRECTORY)
add_test( GraphTest.GetByStringId /home/xjdr/src/xjdr/gg/tests/graph_test [==[--gtest_filter=GraphTest.GetByStringId]==] --gtest_also_run_disabled_tests)
set_tests_properties( GraphTest.GetByStringId PROPERTIES WORKING_DIRECTORY /home/xjdr/src/xjdr/gg/tests VS_DEBUGGER_WORKING_DIRECTORY)
add_test( GraphTest.GetByMId /home/xjdr/src/xjdr/gg/tests/graph_test [==[--gtest_filter=GraphTest.GetByMId]==] --gtest_also_run_disabled_tests)
set_tests_properties( GraphTest.GetByMId PROPERTIES WORKING_DIRECTORY /home/xjdr/src/xjdr/gg/tests VS_DEBUGGER_WORKING_DIRECTORY)
add_test( GraphAlgoTest.CommonNeighbors /home/xjdr/src/xjdr/gg/tests/graph_test [==[--gtest_filter=GraphAlgoTest.CommonNeighbors]==] --gtest_also_run_disabled_tests)
set_tests_properties( GraphAlgoTest.CommonNeighbors PROPERTIES WORKING_DIRECTORY /home/xjdr/src/xjdr/gg/tests VS_DEBUGGER_WORKING_DIRECTORY)
add_test( GraphAlgoTest.JaccardCoefficient /home/xjdr/src/xjdr/gg/tests/graph_test [==[--gtest_filter=GraphAlgoTest.JaccardCoefficient]==] --gtest_also_run_disabled_tests)
set_tests_properties( GraphAlgoTest.JaccardCoefficient PROPERTIES WORKING_DIRECTORY /home/xjdr/src/xjdr/gg/tests VS_DEBUGGER_WORKING_DIRECTORY)
add_test( GraphAlgoTest.AdamicAdar /home/xjdr/src/xjdr/gg/tests/graph_test [==[--gtest_filter=GraphAlgoTest.AdamicAdar]==] --gtest_also_run_disabled_tests)
set_tests_properties( GraphAlgoTest.AdamicAdar PROPERTIES WORKING_DIRECTORY /home/xjdr/src/xjdr/gg/tests VS_DEBUGGER_WORKING_DIRECTORY)
add_test( GraphQueryTest.Author1Wrote /home/xjdr/src/xjdr/gg/tests/graph_test [==[--gtest_filter=GraphQueryTest.Author1Wrote]==] --gtest_also_run_disabled_tests)
set_tests_properties( GraphQueryTest.Author1Wrote PROPERTIES WORKING_DIRECTORY /home/xjdr/src/xjdr/gg/tests VS_DEBUGGER_WORKING_DIRECTORY)
add_test( GraphQueryTest.AuthorsBooks1And3 /home/xjdr/src/xjdr/gg/tests/graph_test [==[--gtest_filter=GraphQueryTest.AuthorsBooks1And3]==] --gtest_also_run_disabled_tests)
set_tests_properties( GraphQueryTest.AuthorsBooks1And3 PROPERTIES WORKING_DIRECTORY /home/xjdr/src/xjdr/gg/tests VS_DEBUGGER_WORKING_DIRECTORY)
add_test( GraphQueryTest.FilterByBook /home/xjdr/src/xjdr/gg/tests/graph_test [==[--gtest_filter=GraphQueryTest.FilterByBook]==] --gtest_also_run_disabled_tests)
set_tests_properties( GraphQueryTest.FilterByBook PROPERTIES WORKING_DIRECTORY /home/xjdr/src/xjdr/gg/tests VS_DEBUGGER_WORKING_DIRECTORY)
set( graph_test_TESTS GraphTest.BasicInsert GraphTest.GetByStringId GraphTest.GetByMId GraphAlgoTest.CommonNeighbors GraphAlgoTest.JaccardCoefficient GraphAlgoTest.AdamicAdar GraphQueryTest.Author1Wrote GraphQueryTest.AuthorsBooks1And3 GraphQueryTest.FilterByBook)
