if(EXISTS "/home/xjdr/src/xjdr/gg/tests/graph_test[1]_tests.cmake")
  include("/home/xjdr/src/xjdr/gg/tests/graph_test[1]_tests.cmake")
else()
  add_test(graph_test_NOT_BUILT graph_test_NOT_BUILT)
endif()
